export const levels = [
  {
    hot_price: 0,
    id: 10,
    mission: "",
    value: 10,
  },
  {
    hot_price: 0,
    id: 11,
    mission: "invite_friend",
    value: 12,
  },
  {
    hot_price: 0,
    id: 12,
    mission: "download_app",
    value: 15,
  },
  {
    hot_price: 0,
    id: 13,
    mission: "deposit_1NEAR",
    value: 18,
  },
  {
    hot_price: 0,
    id: 14,
    mission: "deposit_1USDT",
    value: 20,
  },
  {
    hot_price: 0,
    id: 15,
    mission: "deposit_NFT",
    value: 25,
  },
  {
    hot_price: 0,
    id: 20,
    mission: "",
    value: 720000000000,
  },
  {
    hot_price: 200000,
    id: 21,
    mission: "",
    value: 1080000000000,
  },
  {
    hot_price: 500000,
    id: 22,
    mission: "",
    value: 1440000000000,
  },
  {
    hot_price: 1000000,
    id: 23,
    mission: "",
    value: 2160000000000,
  },
  {
    hot_price: 4000000,
    id: 24,
    mission: "",
    value: 4320000000000,
  },
  {
    hot_price: 10000000,
    id: 25,
    mission: "",
    value: 8640000000000,
  },
  {
    hot_price: 0,
    id: 0,
    mission: "",
    value: 10000,
  },
  {
    hot_price: 200000,
    id: 1,
    mission: "",
    value: 15000,
  },
  {
    hot_price: 1000000,
    id: 2,
    mission: "",
    value: 20000,
  },
  {
    hot_price: 2000000,
    id: 3,
    mission: "",
    value: 25000,
  },
  {
    hot_price: 5000000,
    id: 4,
    mission: "",
    value: 30000,
  },
  {
    hot_price: 15000000,
    id: 5,
    mission: "",
    value: 50000,
  },
  {
    hot_price: 0,
    id: 99,
    mission: "",
    value: 1,
  },
];
export const storeFireplace = [
  {
    id: 0,
    title: "Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
  },
  {
    id: 1,
    title: "Stone Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
  },
  {
    id: 2,
    title: "Gas Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
  },
  {
    id: 3,
    title: "Neon Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
  },
  {
    id: 4,
    title: "Neon Multy-fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
  },
  {
    id: 5,
    title: "Neon Multy-fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
  },
  {
    id: 10,
    title: "Basic Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    mission_text: "",
  },
  {
    id: 11,
    title: "Neon Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    mission_text: "Invite a referral",
  },
  {
    id: 12,
    title: "Titanium Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    mission_text: "Download the mobile app and import your account",
  },
  {
    id: 13,
    title: "Jedi Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    mission_text: "Send 0.5+ NEAR from .near account, created at HERE Wallet",
  },
  
  {
    id: 14,
    title: "Uranium Boxes",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    mission_text: "Deposit 1+ USDT on your account",
  },
  {
    id: 15,
    title: "Uranium Boxes",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    mission_text: "Coming soon...",
  },
  {
    id: 19,
    title: "Super Fuel",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Temporary booster for contest. Gives 5x!",
  },
  {
    id: 20,
    title: "Wooden Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
  },
  {
    id: 21,
    title: "Metal Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
  },
  {
    id: 22,
    title: "Modular Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
  },
  {
    id: 23,
    title: "Liquid Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
  },
  {
    id: 24,
    title: "Titanium Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
  },
  {
    id: 25,
    title: "Titanium Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
  },
  {
    id: 99,
    title: "Rotted Wood",
    text: "You were punished for using automatic mining. Your speed is reduced by 10 times",
    description: "Makanya jangan pake auto mining, wkwkwk dinerf kan",
    mission_text: "",
  },
];
